use aoc20::*;

fn main() {
    let input1 = utils::read_input("input1.txt").unwrap();
    let input2 = utils::read_input("input2.txt").unwrap();
    let input3 = utils::read_input("input3.txt").unwrap();
    let input4 = utils::read_input("input4.txt").unwrap();
    let input5 = utils::read_input("input5.txt").unwrap();
    let input6 = utils::read_input("input6.txt").unwrap();
    let input7 = utils::read_input("input7.txt").unwrap();
    let input8 = utils::read_input("input8.txt").unwrap();
    let input9 = utils::read_input("input9.txt").unwrap();
    let input10 = utils::read_input("input10.txt").unwrap();
    let input11 = utils::read_input("input11.txt").unwrap();
    let input12 = utils::read_input("input12.txt").unwrap();
    let input13 = utils::read_input("input13.txt").unwrap();
    let input14 = utils::read_input("input14.txt").unwrap();
    let input15 = utils::read_input("input15.txt").unwrap();
    let input16 = utils::read_input("input16.txt").unwrap();
    let input17 = utils::read_input("input17.txt").unwrap();
    let input18 = utils::read_input("input18.txt").unwrap();
    let input19 = utils::read_input("input19.txt").unwrap();
    // let input20 = utils::read_input("input20.txt").unwrap();
    let input21 = utils::read_input("input21.txt").unwrap();
    let input22 = utils::read_input("input22.txt").unwrap();
    let input23 = utils::read_input("input23.txt").unwrap();
    let input24 = utils::read_input("input24.txt").unwrap();
    let input25 = utils::read_input("input25.txt").unwrap();
    // let input10big = utils::read_input("10.in").unwrap();
    dbg!(day1::part1(&input1));
    dbg!(day1::part2(&input1));
    dbg!(day2::part1(&input2));
    dbg!(day2::part2(&input2));
    dbg!(day3::part1(&input3));
    dbg!(day3::part2(&input3));
    dbg!(day4::part1(&input4));
    dbg!(day4::part2(&input4));
    dbg!(day5::part1(&input5));
    dbg!(day5::part2(&input5));
    dbg!(day6::part1(&input6));
    dbg!(day6::part2(&input6));
    dbg!(day7::part1(&input7));
    dbg!(day7::part2(&input7));
    dbg!(day8::part1(&input8));
    dbg!(day8::part2(&input8));
    dbg!(day9::part1(&input9));
    dbg!(day9::part2(&input9));
    dbg!(day10::part1(&input10));
    dbg!(day10::part2(&input10));
    dbg!(day11::part1(&input11));
    dbg!(day11::part2(&input11));
    dbg!(day12::part1(&input12));
    dbg!(day12::part2(&input12));
    dbg!(day13::part1(&input13));
    dbg!(day13::part2(&input13));
    dbg!(day14::part1(&input14));
    dbg!(day14::part2(&input14));
    dbg!(day15::part1(&input15));
    dbg!(day15::part2(&input15));
    dbg!(day16::part1(&input16));
    dbg!(day16::part2(&input16));
    dbg!(day17::part1(&input17));
    dbg!(day17::part2(&input17));
    dbg!(day18::part1(&input18));
    dbg!(day18::part2(&input18));
    dbg!(day19::part1(&input19));
    dbg!(day19::part2(&input19));
    // dbg!( day20::part1(&input20));
    // dbg!( day20::part2(&input20));
    dbg!(day21::part1(&input21));
    dbg!(day21::part2(&input21));
    dbg!(day22::part1(&input22));
    dbg!(day22::part2(&input22));
    dbg!(day23::part1(&input23));
    dbg!(day23::part2(&input23));
    dbg!(day24::part1(&input24));
    dbg!(day24::part2(&input24));
    dbg!(day25::part1(&input25));
    dbg!(day25::part2(&input25));
}
